@echo off
SET KEIL_BIN_DIR="E:\Program Files (x86)\ARM\Keil_v5\ARM\ARMCC\bin"
SET PROGRAM_FILE=fromelf.exe

SET AXF_FILE_LOCATION=.\build\Objects
SET AXF_FILE_NAME=IGTx

SET BIN_FILE_LOCATION=.\build\Objects
SET BIN_FILE_NAME=IGTx

REM 构建命令行参数
SET CMD_ARGS=--bin --output %BIN_FILE_LOCATION%\%BIN_FILE_NAME%.bin %AXF_FILE_LOCATION%\%AXF_FILE_NAME%.axf

REM 执行
%KEIL_BIN_DIR%\%PROGRAM_FILE% %CMD_ARGS%
