#ifndef __MY_SERIAL_GPIO_CONF_H__
    #define __MY_SERIAL_GPIO_CONF_H__
    #define SERIAL_COM1_TX_PIN GPIO_PIN_6
    #define SERIAL_COM1_TX_PIN_PORT GPIOB
    #define SERIAL_COM1_RX_PIN GPIO_PIN_7
    #define SERIAL_COM1_RX_PIN_PORT GPIOB
    #define SERIAL_COM1_AF GPIO_AF7_USART1
    #define SERIAL_COM1_PIN_CLK_ENABLE() do { __HAL_RCC_GPIOB_CLK_ENABLE(); } while(0)

    #define SERIAL_COM2_TX_PIN GPIO_PIN_2
    #define SERIAL_COM2_TX_PIN_PORT GPIOA
    #define SERIAL_COM2_RX_PIN GPIO_PIN_3
    #define SERIAL_COM2_RX_PIN_PORT GPIOA
    #define SERIAL_COM2_AF GPIO_AF7_USART2
    #define SERIAL_COM2_PIN_CLK_ENABLE() do { __HAL_RCC_GPIOA_CLK_ENABLE(); } while(0)

    #define SERIAL_COM3_TX_PIN GPIO_PIN_11
    #define SERIAL_COM3_TX_PIN_PORT GPIOB
    #define SERIAL_COM3_RX_PIN GPIO_PIN_10
    #define SERIAL_COM3_RX_PIN_PORT GPIOB
    #define SERIAL_COM3_AF GPIO_AF7_USART3
    #define SERIAL_COM3_PIN_CLK_ENABLE() do { __HAL_RCC_GPIOB_CLK_ENABLE(); } while(0)

    #define SERIAL_COM4_TX_PIN GPIO_PIN_0
    #define SERIAL_COM4_TX_PIN_PORT GPIOA
    #define SERIAL_COM4_RX_PIN GPIO_PIN_1
    #define SERIAL_COM4_RX_PIN_PORT GPIOA
    #define SERIAL_COM4_AF GPIO_AF8_UART4
    #define SERIAL_COM4_PIN_CLK_ENABLE() do { __HAL_RCC_GPIOA_CLK_ENABLE(); } while(0)

    #define SERIAL_COM5_TX_PIN GPIO_PIN_12
    #define SERIAL_COM5_TX_PIN_PORT GPIOC
    #define SERIAL_COM5_RX_PIN GPIO_PIN_2
    #define SERIAL_COM5_RX_PIN_PORT GPIOD
    #define SERIAL_COM5_AF GPIO_AF8_UART5
    #define SERIAL_COM5_PIN_CLK_ENABLE() do { __HAL_RCC_GPIOC_CLK_ENABLE(); __HAL_RCC_GPIOD_CLK_ENABLE(); } while(0)

    #define SERIAL_COM6_TX_PIN GPIO_PIN_6
    #define SERIAL_COM6_TX_PIN_PORT GPIOC
    #define SERIAL_COM6_RX_PIN GPIO_PIN_7
    #define SERIAL_COM6_RX_PIN_PORT GPIOC
    #define SERIAL_COM6_AF GPIO_AF8_USART6
    #define SERIAL_COM6_PIN_CLK_ENABLE() do { __HAL_RCC_GPIOC_CLK_ENABLE(); } while(0)
#endif
