#ifndef __MY_SERIAL_CONF_H__
    #define __MY_SERIAL_CONF_H__
    #define SERIAL_DATA_LENGTH          1024

    #define SERIAL_COM1_DMA_ENABLE 0
    #define SERIAL_COM1_BAUDRATE 115200

    #define SERIAL_COM2_DMA_ENABLE 0
    #define SERIAL_COM2_BAUDRATE 115200

    #define SERIAL_COM3_DMA_ENABLE 0
    #define SERIAL_COM3_BAUDRATE 115200

    #define SERIAL_COM4_DMA_ENABLE 0
    #define SERIAL_COM4_BAUDRATE 115200

    #define SERIAL_COM5_DMA_ENABLE 0
    #define SERIAL_COM5_BAUDRATE 9600

    #define SERIAL_COM6_DMA_ENABLE 0
    #define SERIAL_COM6_BAUDRATE 115200
#endif
